menu:
  首页: /
# 文集: /collection
# 图集: /gallery
  归档: /archives

submenu:
# 订阅RSS: /atom.xml
# 自定义: /customization
# 个人简历: /resume  


widgets:
- search
- category
- archive
# - tag
- tagcloud
# - weibo

excerpt_link: Read More
comment_link: Comments

# header头像
avatar: /assets/avatar/avatar.png
# header右侧图片展示
ad: /assets/img/avatar/hello.jpg


baidu_share: false

# 请到baidu_tongji.ejs中替换代码
baidu_tongji: true

# enable是否开启；height小挂件高度；url替换成自己的微博挂件地址，同步修改url中height的值
weibo:
  enable: false
  height: 800
  url: you_weibo_url

# 评论提供可以选择 duoshuo 或者 wumii，无需评论，此处不填就行。
comment_provider: duoshuo

duoshuo:
  short_name: wudaijun

wumii: 
  relateditems: false
  siteprefix: http://wudaijun.com


#fancybox: false

#google_analytics: false
